// ignore_for_file: unnecessary_this, unnecessary_new

class Autogenerated {
  bool? success;
  String? status;
  String? pagecreatedate;
  List<Tarihtebugun>? tarihtebugun;

  Autogenerated(
      {this.success, this.status, this.pagecreatedate, this.tarihtebugun});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    status = json['status'];
    pagecreatedate = json['pagecreatedate'];
    if (json['tarihtebugun'] != null) {
      tarihtebugun = <Tarihtebugun>[];
      json['tarihtebugun'].forEach((v) {
        tarihtebugun!.add(new Tarihtebugun.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['success'] = this.success;
    data['status'] = this.status;
    data['pagecreatedate'] = this.pagecreatedate;
    if (this.tarihtebugun != null) {
      data['tarihtebugun'] = this.tarihtebugun!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Tarihtebugun {
  String? gun;
  String? ay;
  String? yil;
  String? durum;
  String? olay;

  Tarihtebugun({this.gun, this.ay, this.yil, this.durum, this.olay});

  Tarihtebugun.fromJson(Map<String, dynamic> json) {
    gun = json['Gun'];
    ay = json['Ay'];
    yil = json['Yil'];
    durum = json['Durum'];
    olay = json['Olay'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['Gun'] = this.gun;
    data['Ay'] = this.ay;
    data['Yil'] = this.yil;
    data['Durum'] = this.durum;
    data['Olay'] = this.olay;
    return data;
  }
}
